import IBudgeterConfiguration from "../models/IBudgeterConfiguration";
import IWindowWebConfiguration from "../models/IWindowWebConfiguration";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

console.log(`PRELOAD: ${MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY}`);

export default class WindowWebConfigurationMapper {
    static fromBudgeterConfiguration(config: IBudgeterConfiguration): IWindowWebConfiguration {
        return {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
            nodeIntegration: config.nodeIntegration,
            contextIsolation: config.contextIsolation
        }
    }
}