import {app, ipcMain} from 'electron';
import MainLoggingModule from "./modules/MainLoggingModule";
import MainIpcModule from "./modules/MainIpcModule";
import AppReadyBehavior from "./behaviors/app/AppReadyBehavior";
import WindowAllClosedBehavior from "./behaviors/window/WindowAllClosedBehavior";
import AppActivateBehavior from "./behaviors/app/AppActivateBehavior";
import FilePathRequestBehavior from "./behaviors/file/FilePathPromptRequestBehavior";
import HomeDirectoryPathRequestBehavior from "./behaviors/directory/HomeDirectoryPathRequestBehavior";
import FileContentRequestBehavior from "./behaviors/file/FileContentRequestBehavior";
import FileCreationRequestBehavior from "./behaviors/file/FileCreationRequestBehavior";
import FileDeletionRequestBehavior from "./behaviors/file/FileDeletionRequestBehavior";
import DirectoryContentRequestBehavior from "./behaviors/directory/DirectoryContentRequestBehavior";
import SpendeeExportParsingBehavior from "./behaviors/parsing/SpendeeExportParsingBehavior";
import * as constants from "./constants";
import IpcKey from "./models/IpcKey";
import IpcStatus from "./models/IpcStatus";
import IpcSource from "./models/IpcSource";

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
    app.quit();
}

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

MainLoggingModule.logInfo(IpcSource.Main,"Index",`Webpack Index Entry Point: ${MAIN_WINDOW_WEBPACK_ENTRY}`);
MainLoggingModule.logInfo(IpcSource.Main, "Index",`Webpack Preload Entry Point: ${MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY}`);

app.on(constants.APP_READY_EVENT, () => AppReadyBehavior(MAIN_WINDOW_WEBPACK_ENTRY, MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY));
app.on(constants.APP_ACTIVATE, () => AppActivateBehavior(MAIN_WINDOW_WEBPACK_ENTRY, MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY))
app.on(constants.APP_WINDOW_ALL_CLOSED, () => WindowAllClosedBehavior());

MainIpcModule.on(IpcKey.PROMPT_FILE_PATH, FilePathRequestBehavior);
MainIpcModule.on(IpcKey.HOME_DIRECTORY_PATH, HomeDirectoryPathRequestBehavior);
MainIpcModule.on(IpcKey.FILE_CONTENT, FileContentRequestBehavior);
MainIpcModule.on(IpcKey.FILE_CREATION, FileCreationRequestBehavior);
MainIpcModule.on(IpcKey.FILE_DELETION, FileDeletionRequestBehavior);
MainIpcModule.on(IpcKey.DIRECTORY_CONTENT, DirectoryContentRequestBehavior);
MainIpcModule.on(IpcKey.SPENDEE_EXPORT_PARSING, SpendeeExportParsingBehavior);

MainLoggingModule.logInfo(IpcSource.Main, "Index", "IPC Listeners Attached");